{{- if and .Values.server.enabled .Values.server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edgekit.server.fullname" . }}-data
  labels:
    {{- include "edgekit.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
  {{- end }}
{{- end }}
